# Generated by Django 3.1a1 on 2020-07-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=18)),
                ('IFSCCode', models.CharField(max_length=11)),
                ('city', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('name_of_bank', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
